### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by bamtan** [DuckBoss/JJMumbleBot#1]
Hi, stupid question but how do I run this bot?

Running `python3 MumbleBot.py` outputs nothing, I've filled what I can inside `config.py`. 

I'm on Debian 9 headless, with the requirements installed.

Thanks

**Comment by DuckBoss** [comment]
so to run this, you want to run the folder as a module. So this command is how I run it on my private server:
"python3 JJMumbleBot/".

Make sure that the folder contains everything from the repository, it should automatically run the __main__.py script.

If for some reason you need to run it by specifying the script, you can do:
"python3 __main__.py"

**Comment by DuckBoss** [comment]
I've updated the wiki to address this question:
https://github.com/DuckBoss/JJMumbleBot/wiki/Quick-Start

**Comment by DuckBoss** [comment]
I've updated the wiki to include this information:
https://github.com/DuckBoss/JJMumbleBot/wiki/Quick-Start

**Comment by DuckBoss** [comment]
If everything from above looks fine, then maybe I would suggest deleting the __pycache__ folders in the main directory, plugin directories, and template directory. I've updated the bot to remove these __pycache__ folders. If nothing else works, I suggest updating to the most recent build I've released.

**Comment by bamtan** [comment]
Thanks, I've cloned the newer version. I am able to get an output when I run the folder, but still nothing outputs when running `python MumbleBot.py`.

Anyways, I am now receiving this error

```bash
$ python JJMumbleBot
JJ Mumble Bot Booting...
JJ Mumble Bot Initializing...
User privilege setup complete.

######### Initializing Plugins #########

Uptime Plugin Initialized.
Images Plugin Initialized.
Bot_Commands Plugin Initialized.
Sound_Board Plugin Initialized...
Music Plugin Initialized...
Queue Initialized...
Help Plugin Initialized.

######### Running plugin callback tests #########

Uptime Plugin self-test callback.
Images Plugin self-test callback.
Bot_Commands Plugin self-test callback.
Sound_Board Plugin self-test callback.
Youtube Plugin self-test callback.
Help Plugin self-test callback.
JJ Mumble Bot initialized!

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/bam/.pyenv/versions/3.6.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 114, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occured, exit here
  File "JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 140, in connect
    self.control_socket.connect((self.host, self.port))
  File "/home/bam/.pyenv/versions/3.6.6/lib/python3.6/ssl.py", line 1100, in connect
    self._real_connect(addr, False)
  File "/home/bam/.pyenv/versions/3.6.6/lib/python3.6/ssl.py", line 1087, in _real_connect
    socket.connect(self, addr)
TypeError: an integer is required (got type str)
```

I've tried: 
- Changing the server_ip from a domain to a direct IP address
- leaving user_cert empty

**Comment by DuckBoss** [comment]
I looked back and realized why you can't just start with "python MumbleBot.py". It's because it is a class with no starting point so the program simply runs through without any output and does nothing. This is why you have to start it with the folder.

As far as the error you're getting, is your certificate a .pem file? I haven't seen this error before and I'm trying to figure out what causes it.

**Comment by bamtan** [comment]
My certificate is a .pem file, yes. I used the guide on another project on how to generate one (https://github.com/azlux/botamusique#optional-generate-a-certificate).

I'm using the latest branch of pymumble as pointed to on your project 
```bash
$ git branch
* (HEAD detached at 176a1e9)
  pymumble_py3
```
I've installed all the dependencies inside pymumble as well.

Perhaps I can raise an issue across to pymumble

**Comment by DuckBoss** [comment]
I've looked through the bot and haven't found anything that might trigger this issue. I think you should go ahead and raise the issue in pymumble. I suggest keeping this issue open in case you find anything.

**Comment by bamtan** [comment]
Had a brief conversation with the people at #mumble on the Freenode server, including the pymumble maintainer and have resolved the issue! The problem was having quotes in the `config.py` which weren't required, specifically the `port = PORT_NUMBER`. Bot connects and works fine now. Thanks for your time on this, really appreciate it.

**Comment by DuckBoss** [comment]
Ah yes, the port number must be an integer. I will update the wiki to clarify this for future users. Thank you for your help =)

**Comment by DuckBoss** [comment]
I've created a label for startup issues so that future users may reference it if they encounter problems.
