### ISSUE TITLE
Bot Creates New User Entry in Privileges.csv - User Already Exists

### ISSUE THREAD

**Issue by ChZeman** [DuckBoss/JJMumbleBot#181]
I added my username to privileges.csv, but the bot always adds me again with the lowest user level. I also see the following error message:

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/JJMumbleBot/__main__.py", line 4, in <module>
    JJMumbleBot.JJMumbleBot()
  File "/home/pi/JJMumbleBot/JJMumbleBot.py", line 126, in __init__
    pv.setup_privileges()
  File "/home/pi/JJMumbleBot/privileges.py", line 25, in setup_privileges
    users[row['user']] = int(row['level'])
KeyError: 'level'`

Am I just doing something wrong?

**Comment by DuckBoss** [comment]
Sorry I've been busy, if you're still encountering problems then could you share your permissions csv? I think when you manually added your user to the file you might have not followed the comma-delimiting format correctly which caused the program to not detect your user.

**Comment by DuckBoss** [comment]
Closing issue due to inactivity
