### ISSUE TITLE
 jjmumblebot.db file missing?

### ISSUE THREAD

**Issue by yquemener** [DuckBoss/JJMumbleBot#232]
I followed all the quickstart instructions but when I start

`python JJMumbleBot/`

it fails with this error:

```
[JJMumbleBot(3.1.2).StartUp]:######### Initializing JJMumbleBot #########
[JJMumbleBot(3.1.2).Database]:######### Initializing Internal Database #########
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "JJMumbleBot/__main__.py", line 5, in <module>
    service.BotService()
  File "JJMumbleBot/JJMumbleBot/core/bot_service.py", line 50, in __init__
    db_backup = BotServiceHelper.backup_database()
  File "JJMumbleBot/JJMumbleBot/lib/helpers/bot_service_helper.py", line 187, in backup_database
    copy(src_file, dst_file)
  File "/usr/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'JJMumbleBot/JJMumbleBot/cfg/jjmumblebot.db'
```

If I create an empty file `JJMumbleBot/JJMumbleBot/cfg/jjmumblebot.db` the bit starts but fails on the first command sent with 

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "JJMumbleBot/JJMumbleBot/plugins/core/core_commands/core_commands.py", line 183, in process
    if not privileges.plugin_privilege_checker(text, command, self.plugin_name):
  File "JJMumbleBot/JJMumbleBot/lib/privileges.py", line 63, in plugin_privilege_checker
    if not privileges_check(GS.mumble_inst.users[text.actor]) >= plugin_privileges_check(command, plugin_name):
  File "JJMumbleBot/JJMumbleBot/lib/privileges.py", line 39, in privileges_check
    return int(user_data['level'])
TypeError: 'NoneType' object is not subscriptable
```

I suspect `jjmumblebot.db` was removed in a recent commit. It probably does not break for people who are updating their repos but for newcomers like me it fails.

**Comment by DuckBoss** [comment]
That's odd. The database is not supposed to be included and it is supposed to automatically generate it on launch. Are you using the newest release version?
I'll look into it.

**Comment by DuckBoss** [comment]
The most recent update should have fixed this issue. In addition I've made automatic database backups optional which can be set in your config.ini file.
I suggest waiting for release v3.1.3 to update the bot, which should be ready by the end of the day.

**Comment by DuckBoss** [comment]
Please refer to the new [v3.1.3 Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v3.1.3) for fixes to your issue

**Comment by yquemener** [comment]
It works fine now. Thank!
